version: "3.9"
services: 
    postgres:
        image:  postgres:13.2-alpine
        container_name: postgres-nest
        ports: 
            - "5432:5432"
        volumes: 
            -  $HOME/postgressql/data-nest:/var/lib/postgresql/data
        environment: 
            - POSTGRES_PASSWORD=12345678
            - POSTGRES_DB=nest
    pgAdmin:
        image: dpage/pgadmin4     
        container_name: pgAdmin-nest 
        ports: 
            - "5050:80"
        environment: 
            - PGADMIN_DEFAULT_EMAIL=yanguyt@hotmail.com
            - PGADMIN_DEFAULT_PASSWORD=12345678
        depends_on: 
            - postgres
